version: '3.8'

networks:
  mynetworkapi:

services:
  sql-server-docker:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=TuPassword123!
    networks:
      - mynetworkapi
    volumes:
      - sqldata:/var/opt/mssql




  api-choosing:
    image : ${DOCKER_REGISTRY-}api-choosing
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: api-choosing
    networks:
      - mynetworkapi
    depends_on:
      - sql-server-docker
    ports:
      - "5001:80"  # Mapeamos el puerto 5001 externo al 80 interno
      - "5002:443" # Puerto para HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TuCertPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https:ro 

volumes:
  sqldata: